GET http://localhost:3000/words

###

POST http://localhost:3000/words
Content-Type: application/json

{
    "name":"leeway",
    "meaning":"careful about paying attention to every detail",
    "sentences":"You must be scrupulous about hygiene when you're preparing a baby's feed.\nscrupulous attention to detail"
}

###

GET http://localhost:3000/words/626b0d324770e772206004bd

###

DELETE http://localhost:3000/words/626b26534c24793e6b589adf