GET http://localhost:3000/words

###

POST http://localhost:3000/words
Content-Type: application/json

{
    "name": "vocation",
    "meaning": "a type of work or way of life that you believe is especially suitable for you",
    "sentences": "Nursing is not just a job—it's a vocation.\nShe believes that she has found her true vocation in life.\nYou missed your vocation—you should have been an actor."
}

###

GET http://localhost:3000/words/626b0d324770e772206004bd

###

DELETE http://localhost:3000/words/626b26534c24793e6b589adf